### PR TITLE
Autocomplete UI

### LINKED ISSUE #4: Prepare autocomplete UI
Use [MUI autocomplete](https://mui.com/material-ui/react-autocomplete/) for autocomplete and [`notistack`](https://notistack.com/) for the error messages

DoD:
1. UI that consists of an input
2. Prepare a list of hardcoded items (5-10 city names)
3. All requests should be debounced - the app shouldn't fire request oftener that 400ms
4. Depending on input state:
    a. if the input is empty - clear search results, don't show suggestions
    b. if the input is filled - initiate search in hardcoded data. After this a list of filtered cities should appear.
    c. At least 2 characters are required for search initiation
5. Add a state that keeps user selection
6. Prepare this UIs: 
    a. UI of not selected suggestion
    b. UI of selected suggestion
    c. UI when no data is found
    d. Loading indicator for the input
    e. Add snackbar if fetch is failed

### PR DESCRIPTION
**Pull request by coding-vibe**

### CODE REVIEW

File: src/components/Autocomplete/Autocomlete.tsx [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+import debounce from 'lodash.debounce';
+import { SnackbarProvider, enqueueSnackbar } from 'notistack';
+import { CITIES } from './citiesList';
+
+export default function Autocomplele() {
+  const [value, setValue] = useState<string>('');
+  // const [value, setValue] = useState(CITIES[0]);
+  const [inputValue, setInputValue] = useState<string>('');
+  const [options, setOptions] = useState<string[]>([]);
+  const DEBOUNCE_DELAY = 400;
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Move me out of component

File: src/components/Autocomplete/Autocomlete.tsx [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+
+  const onChange = debounce((e: SyntheticEvent, v: string | null) => {
+    if (v !== null) {
+      setValue(v);
+    }
+  }, DEBOUNCE_DELAY);
+
+  const onInputChange = debounce((e: SyntheticEvent, v: string) => {
+    const trimmedValue = v.trim();
+    if (trimmedValue === '' || trimmedValue.length <= 2) {
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Min value - to const

File: src/components/Autocomplete/Autocomlete.tsx [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+  const [options, setOptions] = useState<string[]>([]);
+  const DEBOUNCE_DELAY = 400;
+
+  const onChange = debounce((e: SyntheticEvent, v: string | null) => {
+    if (v !== null) {
+      setValue(v);
+    }
+  }, DEBOUNCE_DELAY);
+
+  const onInputChange = debounce((e: SyntheticEvent, v: string) => {
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Shouldn't be debounced

File: src/components/Autocomplete/Autocomlete.tsx [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+
+  return (
+    <>
+      <SnackbarProvider />
+      <Autocomplete
+        disablePortal
+        disableCloseOnSelect
+        id='cities-select'
+        options={options}
+        sx={{ width: 300 }}
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Move me to a separate file with styles

File: src/components/Autocomplete/Autocomlete.tsx [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+    setInputValue(trimmedValue);
+    setOptions(CITIES);
+  }, DEBOUNCE_DELAY);
+
+  // console.log(inputValue);
+  console.log(value);
+
+  return (
+    <>
+      <SnackbarProvider />
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Move me to entry point

File: src/components/Autocomplete/Autocomlete.tsx [hunk 6]
```diff
@@ -0,0 +1,62 @@
+/* eslint-disable no-unused-vars */
+/* eslint-disable @typescript-eslint/no-unused-vars */
+import { SyntheticEvent, useState } from 'react';
+import Autocomplete from '@mui/material/Autocomplete';
+import TextField from '@mui/material/TextField';
+import debounce from 'lodash.debounce';
+import { SnackbarProvider, enqueueSnackbar } from 'notistack';
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Let's use `useSnackbar`

File: src/components/Autocomplete/Autocomlete.tsx [hunk 7]
```diff
@@ -0,0 +1,62 @@
+/* eslint-disable no-unused-vars */
+/* eslint-disable @typescript-eslint/no-unused-vars */
+import { SyntheticEvent, useState } from 'react';
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Also, check all imports of react and add ESLint rule that makes this import redundant

File: src/components/Autocomplete/Autocomlete.tsx [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+import Autocomplete from '@mui/material/Autocomplete';
+import TextField from '@mui/material/TextField';
+import debounce from 'lodash.debounce';
+import { SnackbarProvider, enqueueSnackbar } from 'notistack';
+import { CITIES } from './citiesList';
+
+export default function Autocomplele() {
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Correct name of component and filename

File: src/components/Autocomplete/Autocomlete.tsx [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+  const [value, setValue] = useState<string>('');
+  // const [value, setValue] = useState(CITIES[0]);
+  const [inputValue, setInputValue] = useState<string>('');
+  const [options, setOptions] = useState<string[]>([]);
+  const DEBOUNCE_DELAY = 400;
+
+  const onChange = debounce((e: SyntheticEvent, v: string | null) => {
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Use `_` for omitted arguments

File: src/components/Autocomplete/Autocomlete.tsx [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+    if (trimmedValue === '' || trimmedValue.length <= 2) {
+      setInputValue('');
+      setOptions([]);
+      enqueueSnackbar(
+        `Sorry, we couldn't find any results that match your search. You should enter more than 2 letters and make sure that an existing city is included in the search`,
+      );
+      return;
+    }
+    setInputValue(trimmedValue);
+    setOptions(CITIES);
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Add logic for filtering by input value. They should filtered after 1 sec delay

File: src/components/Autocomplete/Autocomlete.tsx (hunk 9 above)
Comment (singvarr) [reply src/components/Autocomplete/Autocomlete.tsx]: Add check of `reason`

File: src/components/Autocomplete/Autocomlete.tsx [hunk 11]
```diff
@@ -0,0 +1,62 @@
...
+
+export default function Autocomplele() {
+  const [value, setValue] = useState<string>('');
+  // const [value, setValue] = useState(CITIES[0]);
+  const [inputValue, setInputValue] = useState<string>('');
+  const [options, setOptions] = useState<string[]>([]);
+  const DEBOUNCE_DELAY = 400;
+
+  const onChange = debounce((e: SyntheticEvent, v: string | null) => {
+    if (v !== null) {
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: `if (value)
```suggestion
    if (v !== null) {
````

File: src/components/Autocomplete/Autocomlete.tsx [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+
+  const onInputChange = debounce((e: SyntheticEvent, v: string) => {
+    const trimmedValue = v.trim();
+    if (trimmedValue === '' || trimmedValue.length <= 2) {
+      setInputValue('');
+      setOptions([]);
+      enqueueSnackbar(
+        `Sorry, we couldn't find any results that match your search. You should enter more than 2 letters and make sure that an existing city is included in the search`,
+      );
+      return;
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: I prefer move logic after this `if` to `else`

File: src/components/Autocomplete/Autocomlete.tsx [hunk 13]
```diff
@@ -0,0 +1,62 @@
...
+export default function Autocomplele() {
+  const [value, setValue] = useState<string>('');
+  // const [value, setValue] = useState(CITIES[0]);
+  const [inputValue, setInputValue] = useState<string>('');
+  const [options, setOptions] = useState<string[]>([]);
+  const DEBOUNCE_DELAY = 400;
+
+  const onChange = debounce((e: SyntheticEvent, v: string | null) => {
+    if (v !== null) {
+      setValue(v);
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Check your debounce. Now it doesn't work

File: src/components/Autocomplete/Autocomlete.tsx [hunk 14]
```diff
@@ -0,0 +1,62 @@
+/* eslint-disable no-unused-vars */
+/* eslint-disable @typescript-eslint/no-unused-vars */
+import { SyntheticEvent, useState } from 'react';
+import Autocomplete from '@mui/material/Autocomplete';
+import TextField from '@mui/material/TextField';
+import debounce from 'lodash.debounce';
```
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Install `lodash`. Use individual imports - like `import debounce from 'lodash/debounce';`
Also, reinstall types for all library

**Review by singvarr — APPROVED** [review]

**Comment by singvarr** [comment]
Please, correct these comments)

File: src/components/Autocomplete/Autocomlete.tsx (hunk 7 above)
Comment (singvarr) [inline src/components/Autocomplete/Autocomlete.tsx]: Also don't forget to add `index.ts` for reexport

File: src/components/AutocompleteInput/AutocompleteInput.tsx [hunk 15]
```diff
@@ -0,0 +1,102 @@
...
+const TIMEOUT_DELAY = 1000;
+const DEBOUNCE_DELAY = 400;
+const MIN_INPUT_LEN = 2;
+const FAILED_FETCH_MESSAGE = `Sorry, we couldn't find any results that match your search. You should enter more than 2 letters and make sure that an existing city is included in the search`;
+const NO_OPTIONS_TEXT = `Sorry, we couldn't find any results that match your search.`;
+
+export default function AutocompleteInput() {
+  const [options, setOptions] = useState<string[]>([]);
+  const [isFirstInput, setIsFirstInput] = useState(true);
+  const [inputValue, setInputValue] = useState<string>('');
```
Comment (singvarr) [inline src/components/AutocompleteInput/AutocompleteInput.tsx:21]: const [, setInputValue] = useState<string>('');
